### ISSUE TITLE
Hi, help me

### ISSUE THREAD

**Issue by FullZero5** [Awilum/morfy-cms#24]
Added a new theme and all error

Warning: require(/home/u351204865/public_html/themes/‘redline’/index.html): failed to open stream: No such file or directory in /home/u351204865/public_html/libraries/Morfy/Morfy.php on line 193

Fatal error: require(): Failed opening required '/home/u351204865/public_html/themes/‘redline’/index.html' (include_path='.:/opt/php-5.5/pear') in /home/u351204865/public_html/libraries/Morfy/Morfy.php on line 193
files exist

**Comment by Awilum** [comment]
Have you done this ?

1. You need to recursively CHMOD the folder /content/, /themes/ to 755(or 777) if your host doesn't set it implicitly.

2. You need update confing file. - confing.php. Set your theme there.

**Comment by FullZero5** [comment]
1.I installed ok
2.He created a new topic and poured it on ftp
3.Edit config  'site_theme' => 'mytheme',
and all the error

**Comment by pafnuty** [comment]
Check the owner of files?

**Comment by FullZero5** [comment]
problem was solved
1.Save config
2.Add install.php
3.Please replace the back config.php
