### ISSUE TITLE
В dev потерялся логотип?

### ISSUE THREAD

**Issue by pafnuty** [Awilum/morfy-cms#32]

**Comment by Awilum** [comment]
если вы про битую ссылку на картинку при инсталяции, то да. не запушил логотип еще

**Comment by pafnuty** [comment]
Да, про него. Решил на всякий случай обратить внимание, чтобы в мастер не попало.

**Comment by Awilum** [comment]
fixed https://github.com/Awilum/morfy-cms/commit/da163342b31ca57c3f9c6eea083bdee3cfb4aa7f
